-- Crear procedure para gestionar el salario de un empleado por su nombre
CREATE PROCEDURE SP_EVALUAR_SUELDO_EMP
(@APELLIDO NVARCHAR(50)) AS
	DECLARE @SUELDO INT
	SELECT @SUELDO = SALARIO FROM EMP WHERE APELLIDO=@APELLIDO
	IF (@SUELDO < 150000)
	BEGIN 
		UPDATE EMP SET SALARIO = SALARIO + 10000
		WHERE APELLIDO = @APELLIDO
		--BUENA PRAXIS INCLUIR LO QUE SUCEDER EN LAS ACCIONES
		PRINT 'SUBIMOS SALARIO ' 
		+ @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
	END
	ELSE IF (@SUELDO > 250000)
	BEGIN
		UPDATE EMP SET SALARIO = SALARIO - 2000
		WHERE APELLIDO = @APELLIDO
		PRINT 'BAJAMOS SALARIO ' + @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
	END
	ELSE
	BEGIN
		PRINT 'SALARIO SIN MODIFICACIONES ' + @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
	END
GO
EXEC SP_EVALUAR_SUELDO_EMP 'REY';

/*
	enviamos el nombre del hospital, si el hospital no existe, no insertamos
*/
CREATE PROCEDURE SP_INSERT_DOCTOR
(@APELLIDO NVARCHAR(50), @ESPECIALIDAD NVARCHAR(50), @SALARIO INT, @NOMBREHOSPITAL NVARCHAR(50))
AS
	DECLARE @IDDOCTOR INT
	DECLARE @IDHOSPITAL INT
	
	SELECT @IDHOSPITAL = HOSPITAL_COD FROM HOSPITAL
	WHERE NOMBRE = @NOMBREHOSPITAL;
	
	IF(@IDHOSPITAL IS NULL) BEGIN
		PRINT 'EL HOSPITAL NO EXISTE'
	END
	ELSE BEGIN
		SELECT @IDDOCTOR = MAX(DOCTOR.DOCTOR_NO) + 1 FROM DOCTOR;
		INSERT INTO HOSPITAL VALUES (@IDHOSPITAL, @IDDOCTOR, @APELLIDO, @ESPECIALIDAD, @SALARIO);
		PRINT 'DOCTOR INSERTADO CON EXITO'
	END
GO

EXEC SP_INSERT_DOCTOR 'HOUSE', 'DIAGNOSTICO', 500000, 'GENERAL';

/*
	Procedimiento que devuelve un valor
*/
CREATE PROCEDURE SP_EMPLEADOS_DEPT_OUT
(@IDDEPT INT, @SUMASALARIAL INT OUT)
AS
	SELECT * FROM EMP
	WHERE DEPT_NO = @IDDEPT;

	-- Asignar algun valor al parametro de salida para deolverlo con valor en la peticion
	SELECT @SUMASALARIAL = SUM(SALARIO) FROM EMP WHERE DEPT_NO = @IDDEPT;
GO

/*
	Para la llamada a un procedimiento almacenado con 
	parametros de salida es necesario utilizar variables
	en la peticion
*/
DECLARE @SUMASALARIAL INT
EXEC SP_EMPLEADOS_DEPT_OUT 20, @SUMASALARIAL OUTPUT

SELECT @SUMASALARIAL AS SUMA_SALARIAL;