-- Crear procedure para gestionar el salario de un empleado por su nombre
CREATE PROCEDURE SP_EVALUAR_SUELDO_EMP
(@APELLIDO NVARCHAR(50)) AS
	DECLARE @SUELDO INT
	SELECT @SUELDO = SALARIO FROM EMP WHERE APELLIDO=@APELLIDO
	IF (@SUELDO < 150000)
	BEGIN 
		UPDATE EMP SET SALARIO = SALARIO + 10000
		WHERE APELLIDO = @APELLIDO
		--BUENA PRAXIS INCLUIR LO QUE SUCEDER EN LAS ACCIONES
		PRINT 'SUBIMOS SALARIO ' 
		+ @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
	END
	ELSE IF (@SUELDO > 250000)
	BEGIN
		UPDATE EMP SET SALARIO = SALARIO - 2000
		WHERE APELLIDO = @APELLIDO
		PRINT 'BAJAMOS SALARIO ' + @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
	END
	ELSE
	BEGIN
		PRINT 'SALARIO SIN MODIFICACIONES ' + @APELLIDO + ': ' + CAST(@SUELDO AS NVARCHAR)
	END
GO
EXEC SP_EVALUAR_SUELDO_EMP 'REY';

/*
	enviamos el nombre del hospital, si el hospital no existe, no insertamos
*/
CREATE PROCEDURE SP_INSERT_DOCTOR
(@APELLIDO NVARCHAR(50), @ESPECIALIDAD NVARCHAR(50), @SALARIO INT, @NOMBREHOSPITAL NVARCHAR(50))
AS
	DECLARE @IDDOCTOR INT
	DECLARE @IDHOSPITAL INT
	
	SELECT @IDHOSPITAL = HOSPITAL_COD FROM HOSPITAL
	WHERE NOMBRE = @NOMBREHOSPITAL;
	
	IF(@IDHOSPITAL IS NULL) BEGIN
		PRINT 'EL HOSPITAL NO EXISTE'
	END
	ELSE BEGIN
		SELECT @IDDOCTOR = MAX(DOCTOR.DOCTOR_NO) + 1 FROM DOCTOR;
		INSERT INTO HOSPITAL VALUES (@IDHOSPITAL, @IDDOCTOR, @APELLIDO, @ESPECIALIDAD, @SALARIO);
		PRINT 'DOCTOR INSERTADO CON EXITO'
	END
GO

EXEC SP_INSERT_DOCTOR 'HOUSE', 'DIAGNOSTICO', 500000, 'GENERAL';

/*
	Procedimiento que devuelve un valor
*/
CREATE PROCEDURE SP_EMPLEADOS_DEPT_OUT
(@IDDEPT INT, @SUMASALARIAL INT OUT)
AS
	SELECT * FROM EMP
	WHERE DEPT_NO = @IDDEPT;

	-- Asignar algun valor al parametro de salida para deolverlo con valor en la peticion
	SELECT @SUMASALARIAL = SUM(SALARIO) FROM EMP WHERE DEPT_NO = @IDDEPT;
GO

/*
	Para la llamada a un procedimiento almacenado con 
	parametros de salida es necesario utilizar variables
	en la peticion
*/
DECLARE @SUMASALARIAL INT
EXEC SP_EMPLEADOS_DEPT_OUT 20, @SUMASALARIAL OUTPUT

SELECT @SUMASALARIAL AS SUMA_SALARIAL;

/*
	Procedure del ejercicio para actualizar el salario de un hospital si supera el millon
*/
CREATE PROCEDURE SP_HOSPITALES
AS
	SELECT * FROM HOSPITAL;
GO

CREATE OR ALTER PROCEDURE SP_UPDATESALARIOSHOSPITAL
(@NOMBRE NVARCHAR(50), @INCREMENTO INT = 1000)
AS
	DECLARE @SUELDO_TOTAL INT
	DECLARE @HOSPITALCOD INT

	SELECT @HOSPITALCOD = HOSPITAL_COD FROM HOSPITAL WHERE NOMBRE = @NOMBRE;
	SELECT * FROM PLANTILLA WHERE HOSPITAL_COD = @HOSPITALCOD;

	SELECT @SUELDO_TOTAL = SUM(CAST(SALARIO AS int)) FROM PLANTILLA
	WHERE HOSPITAL_COD = @HOSPITALCOD;

	IF(@SUELDO_TOTAL > 1000000) BEGIN
		UPDATE PLANTILLA SET SALARIO = SALARIO - @INCREMENTO
        WHERE HOSPITAL_COD = @HOSPITALCOD
        PRINT 'BAJANDO SALARIOS: ' + CAST(@SUELDO_TOTAL AS NVARCHAR)
	END
	ELSE BEGIN
        UPDATE PLANTILLA SET SALARIO = SALARIO + @INCREMENTO
        WHERE HOSPITAL_COD = @HOSPITALCOD
        PRINT 'SUBIENDO SALARIOS: ' + CAST(@SUELDO_TOTAL AS NVARCHAR)
	END
GO

/*
	Procedures Form08
*/
CREATE OR ALTER PROCEDURE SP_DEPARTAMENTOS
AS
	SELECT * FROM DEPT;
GO

CREATE OR ALTER PROCEDURE SP_INSERT_DEPARTAMENTO
(@ID INT, @NOMBRE NVARCHAR(50), @LOCALIDAD NVARCHAR(50))
AS
	-- No queremos localidades en Teruel
	IF(@LOCALIDAD = 'TERUEL') BEGIN
		PRINT 'TERUEL NO EXISTE'
	END
	ELSE BEGIN
		INSERT INTO DEPT VALUES(@ID, @NOMBRE, @LOCALIDAD);
	END
GO

CREATE OR ALTER PROCEDURE SP_EMPLEADOS_DEPT
(@DEPT_NO INT,
@SUMA INT OUT,
@MEDIA INT OUT,
@PERSONAS INT OUT)
AS
	SELECT * FROM EMP WHERE EMP.DEPT_NO = @DEPT_NO;
	SELECT @SUMA = SUM(SALARIO), @MEDIA = AVG(SALARIO), @PERSONAS = COUNT(EMP_NO)
	FROM EMP
	WHERE DEPT_NO = @DEPT_NO;
GO

/*
	Procedures Form10
*/
CREATE OR ALTER PROCEDURE SP_HOSPITALES
AS
	SELECT * FROM HOSPITAL;
GO

CREATE OR ALTER PROCEDURE SP_EMPLEADOS_HOSPITAL
(@HOSPITAL_COD INT,
@SUMA INT OUT,
@MEDIA INT OUT,
@PERSONAS INT OUT)
AS
	-- Get empleados
	SELECT APELLIDO, SALARIO, EMPLEADO_NO FROM PLANTILLA WHERE HOSPITAL_COD = @HOSPITAL_COD
	UNION
	SELECT APELLIDO, SALARIO, DOCTOR_NO FROM DOCTOR WHERE HOSPITAL_COD = @HOSPITAL_COD;

	-- Get max, media, personas
	--SELECT @SUMA = SUM(SALARIO), @MEDIA = AVG(SALARIO), @PERSONAS = COUNT(EMPLEADO_NO)
	--FROM PLANTILLA
	--WHERE HOSPITAL_COD = @HOSPITAL_COD
	--UNION
	--SELECT * FROM DOCTOR WHERE HOSPITAL_COD = @HOSPITAL_COD;
	--SELECT @SUMA = SUM(SALARIO), @MEDIA = AVG(SALARIO), @PERSONAS = COUNT(DOCTOR_NO)
	--FROM DOCTOR
	--WHERE HOSPITAL_COD = @HOSPITAL_COD;

	SELECT @SUMA = SUM(SALARIO), @MEDIA = AVG(SALARIO), @PERSONAS = COUNT(PERSONAS) FROM
	 (
		SELECT SALARIO, EMPLEADO_NO AS PERSONAS
		FROM PLANTILLA
		WHERE HOSPITAL_COD = @HOSPITAL_COD 
		UNION
		SELECT SALARIO, DOCTOR_NO
		FROM DOCTOR
		WHERE HOSPITAL_COD = @HOSPITAL_COD
	 ) AS QUERY;
GO