-- Procedimiento para buscar empleados por su salario
CREATE PROCEDURE SP_BUSCADOR_SALARIO
(@SALARIO INT)
AS
	SELECT * FROM EMP
	WHERE SALARIO >= @SALARIO
GO

EXEC SP_BUSCADOR_SALARIO 35000;

CREATE PROCEDURE SP_INSERT_DEPT
(@NUM INT, @NOM NVARCHAR(50), @LOC NVARCHAR(50))
AS
	INSERT INTO DEPT VALUES (@NUM, @NOM, @LOC)
GO

EXEC SP_INSERT_DEPT 55, 'RRHH', 'OVIEDO';

SELECT * FROM DEPT;
