CREATE OR ALTER PROCEDURE SP_CREATE_HOSPITAL
(@HOSPITAL_COD INT, @NOMBRE NVARCHAR(50), @DIRECCION NVARCHAR(50), @TELEFONO NVARCHAR(50), @NUM_CAMA INT)
AS
	INSERT INTO HOSPITAL VALUES (@HOSPITAL_COD, @NOMBRE, @DIRECCION, @TELEFONO, @NUM_CAMA);
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_HOSPITAL
(@HOSPITAL_COD INT, @NOMBRE NVARCHAR(50), @DIRECCION NVARCHAR(50), @TELEFONO NVARCHAR(50), @NUM_CAMA INT)
AS
	UPDATE HOSPITAL SET NOMBRE = @NOMBRE, DIRECCION = @DIRECCION, TELEFONO = @TELEFONO, NUM_CAMA = @NUM_CAMA
	WHERE HOSPITAL_COD = @HOSPITAL_COD;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_HOSPITAL
(@HOSPITAL_COD INT)
AS
	DELETE FROM HOSPITAL WHERE HOSPITAL_COD = @HOSPITAL_COD;
GO