CREATE OR REPLACE PROCEDURE SP_CREATE_HOSPITAL
(P_HOSPITAL_COD HOSPITAL.HOSPITAL_COD%TYPE, P_NOMBRE HOSPITAL.NOMBRE%TYPE, P_DIRECCION HOSPITAL.DIRECCION%TYPE, P_TELEFONO HOSPITAL.TELEFONO%TYPE, P_NUM_CAMA HOSPITAL.NUM_CAMA%TYPE)
AS
BEGIN
  INSERT INTO HOSPITAL VALUES (P_HOSPITAL_COD, P_NOMBRE, P_DIRECCION, P_TELEFONO, P_NUM_CAMA);
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SP_UPDATE_HOSPITAL
(P_HOSPITAL_COD HOSPITAL.HOSPITAL_COD%TYPE, P_NOMBRE HOSPITAL.NOMBRE%TYPE, P_DIRECCION HOSPITAL.DIRECCION%TYPE, P_TELEFONO HOSPITAL.TELEFONO%TYPE, P_NUM_CAMA HOSPITAL.NUM_CAMA%TYPE)
AS
BEGIN
  UPDATE HOSPITAL SET NOMBRE = P_NOMBRE, DIRECCION = P_DIRECCION, TELEFONO = P_TELEFONO, NUM_CAMA = P_NUM_CAMA WHERE HOSPITAL_COD = P_HOSPITAL_COD;
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE SP_DELETE_HOSPITAL
(P_HOSPITAL_COD HOSPITAL.HOSPITAL_COD%TYPE)
AS
BEGIN
  DELETE FROM HOSPITAL WHERE HOSPITAL_COD = P_HOSPITAL_COD;
  COMMIT;
END;

DROP PROCEDURE SP_CREATE_HOSPITAL;
DROP PROCEDURE SP_UPDATE_HOSPITAL;
DROP PROCEDURE SP_DELETE_HOSPITAL;

SELECT * FROM HOSPITAL;
