-- INSERT
INSERT INTO DEPT VALUES (50, 'INFORMATICA', 'GIJON');
INSERT INTO DEPT (DEPT_NO, LOC) VALUES (60, 'OVIEDO');

SELECT * FROM DEPT;

INSERT INTO DEPT VALUES ((SELECT MAX(DEPT_NO) + 1 FROM DEPT), 'INFORMATICA', 'GIJON');

-- 1) INSERTA SI EXISTE LA TABLA
INSERT INTO DEPARTAMENTOS SELECT * FROM DEPT;
-- 2) INSERTA Y CREA LA TABLA SINO EXISTE
SELECT * INTO DEPARTAMENTOS FROM DEPT;
SELECT APELLIDO, OFICIO, SALARIO INTO ANALISTAS
FROM EMP
WHERE OFICIO = 'ANALISTA';

SELECT * FROM ANALISTAS;
SELECT * FROM DEPARTAMENTOS;
