-- Mostrar el apellido y el nombre del departamento de los empleados
SELECT EMP.APELLIDO, DEPT.DNOMBRE
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;

-- Podemos utilizar alias para las tablas
SELECT E.APELLIDO, D.DNOMBRE
FROM EMP E
INNER JOIN DEPT D
ON E.DEPT_NO = D.DEPT_NO;

/*
	• INNER JOIN: Devuelve todos los resultados que combinen entre las dos tablas
	• LEFT JOIN: Devuelve los resultados que combinen y también los resultados de la 
	Tabla de la izquierda
	• RIGHT JOIN: Devuelve los resultados que combinen y también los resultados de la 
	Tabla de la derecha
	• FULL JOIN: Devuelve los resultados que combinen y los que no combinen también
	• CROSS JOIN: Devuelve el producto cartesiano entre las dos tablas
*/

SELECT * FROM DEPT;
SELECT DISTINCT DEPT_NO FROM EMP;

INSERT INTO EMP VALUES
(1111, 'NUEVO', 'ALUMNO', 7839, GETDATE(), 0, 0, 50);

SELECT * FROM EMP;



SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;

SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE
FROM EMP
RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;

SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE
FROM EMP
LEFT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;

SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE
FROM EMP
FULL JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO;

SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE
FROM EMP
CROSS JOIN DEPT;

SELECT EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE
FROM EMP
INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
WHERE DEPT.DNOMBRE = 'VENTAS';

SELECT MAX(SALARIO) AS MAXIMO, DEPT_NO
FROM EMP GROUP BY DEPT_NO;

-- Saber cuantos empleados trabajan en cada departamento
SELECT COUNT(EMP.EMP_NO) AS NUM_EMP, DEPT.DNOMBRE, DEPT.DEPT_NO
FROM EMP RIGHT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.DNOMBRE, DEPT.DEPT_NO;

SELECT COUNT(EMP.EMP_NO) AS NUM_EMP, DEPT.DNOMBRE, DEPT.DEPT_NO
FROM EMP LEFT JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.DNOMBRE, DEPT.DEPT_NO;

SELECT COUNT(EMP.EMP_NO) AS NUM_EMP, DEPT.DNOMBRE, DEPT.DEPT_NO
FROM EMP INNER JOIN DEPT
ON EMP.DEPT_NO = DEPT.DEPT_NO
GROUP BY DEPT.DNOMBRE, DEPT.DEPT_NO;

SELECT COUNT(EMP.EMP_NO) AS NUM_EMP, EMP.DEPT_NO
FROM EMP
GROUP BY EMP.DEPT_NO;

--  Queremos mostrar el apellio, funcion, nombre del hospital, y nombre de la sala de los empleados de la plantilla
SELECT P.APELLIDO, P.FUNCION, H.NOMBRE AS NOMBRE_HOSPITAL, S.NOMBRE AS NOMBRE_SALA
FROM PLANTILLA P
INNER JOIN HOSPITAL H
ON H.HOSPITAL_COD = P.HOSPITAL_COD
INNER JOIN SALA S
ON S.HOSPITAL_COD = P.HOSPITAL_COD
AND S.SALA_COD = P.SALA_COD; -- Metemos el AND ya que por defecto, devolverá todos los resultados de juntar la plantilla, con las funciones, los hospitales, etc

SELECT P.APELLIDO, P.FUNCION, H.NOMBRE AS NOMBRE_HOSPITAL, S.NOMBRE AS NOMBRE_SALA
FROM PLANTILLA P
INNER JOIN SALA S
ON S.HOSPITAL_COD = P.HOSPITAL_COD
AND S.SALA_COD = P.SALA_COD -- Metemos el AND ya que por defecto, devolverá todos los resultados de juntar la plantilla, con las funciones, los hospitales, etc
INNER JOIN HOSPITAL H
ON H.HOSPITAL_COD = S.HOSPITAL_COD;
