SELECT MAX(SALARIO) FROM EMP;
SELECT * FROM EMP WHERE SALARIO = 650000;

SELECT * FROM EMP
WHERE SALARIO = (SELECT MAX(SALARIO) FROM EMP);

-- Si la subconsulta devuelve mas de un valor debemos de utilizar IN
-- Devolver todos los empleados que tienen el mismo oficio que REY
SELECT * FROM EMP
WHERE OFICIO = (SELECT OFICIO FROM EMP WHERE EMP.APELLIDO='REY');
-- Devolver todos los empleados que tienen el mismo oficio que SANCHA, JIMENEZ
SELECT * FROM EMP WHERE OFICIO IN
(SELECT OFICIO FROM EMP WHERE APELLIDO = 'SANCHA' OR APELLIDO='JIMENEZ');

-- UNION permite realizar estas tres consultas en una:
-- Mostrar apellido y salario de los empleados
SELECT APELLIDO, SALARIO FROM EMP;
-- Mostrar apellido y salario de doctores
SELECT APELLIDO, SALARIO FROM DOCTOR;
-- Mostrar apellido y salario de plantilla
SELECT APELLIDO, SALARIO FROM PLANTILLA;

-- Mostrar apellido y salario de todos los empleados
SELECT APELLIDO, SALARIO FROM EMP
UNION
SELECT APELLIDO, SALARIO FROM DOCTOR
UNION
SELECT APELLIDO, SALARIO FROM PLANTILLA;

SELECT APELLIDO, SALARIO AS 'SUELDO' FROM EMP
UNION
SELECT APELLIDO, SALARIO AS 'PASTA' FROM DOCTOR
UNION
SELECT LOC, DEPT_NO FROM DEPT
ORDER BY SUELDO;

SELECT APELLIDO, SALARIO AS SUELDO, OFICIO FROM EMP
UNION
SELECT APELLIDO, SALARIO, ESPECIALIDAD FROM DOCTOR
UNION
SELECT APELLIDO, SALARIO, FUNCION FROM PLANTILLA
ORDER BY SUELDO;

-- Mostrar el apellido y salario de los empleados que cobres mas de 220.000
SELECT APELLIDO, SALARIO FROM EMP
WHERE SALARIO > 220000
UNION
SELECT APELLIDO, SALARIO FROM DOCTOR
WHERE SALARIO > 220000
UNION
SELECT APELLIDO, SALARIO FROM PLANTILLA
WHERE SALARIO > 220000
ORDER BY SALARIO;

SELECT SALARIO FROM 
(SELECT SALARIO FROM EMP
UNION
SELECT SALARIO FROM DOCTOR
UNION
SELECT SALARIO FROM PLANTILLA) AS SALARIO
WHERE SALARIO > 220000;

SELECT APELLIDO, SALARIO AS SUELDO, OFICIO, 'EMP' AS TABLA FROM EMP
WHERE SALARIO > 220000
UNION
SELECT APELLIDO, SALARIO, ESPECIALIDAD, 'DOCTOR' FROM DOCTOR
WHERE SALARIO > 220000
UNION
SELECT APELLIDO, SALARIO, FUNCION, 'PLANTILLA' FROM PLANTILLA
WHERE SALARIO > 220000
ORDER BY SALARIO;

-- SELECT TO SELECT
SELECT TABLA_AUX.APELLIDO, TABLA_AUX.SALARIO, TABLA FROM 
(SELECT APELLIDO, SALARIO, 'EMP' AS TABLA FROM EMP
UNION
SELECT APELLIDO, SALARIO, 'DOCTOR' FROM DOCTOR
UNION
SELECT APELLIDO, SALARIO, 'PLANTILLA' FROM PLANTILLA) AS TABLA_AUX
WHERE TABLA_AUX.SALARIO > 220000
ORDER BY SALARIO;

SELECT APELLIDO, FUNCION,
	CASE T
		WHEN 'M' THEN 'MAÑANA'
		WHEN 'T' THEN 'TARDE'
		ELSE 'NOCHE'
	END AS TURNO
FROM PLANTILLA
